// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPm8UyyzE5MWuWrE3E0-h4pZ77cgyzsGk',
    appId: '1:202409214260:web:3c458aed3b8275b366e561',
    messagingSenderId: '202409214260',
    projectId: 'slideme-87da5',
    authDomain: 'slideme-87da5.firebaseapp.com',
    storageBucket: 'slideme-87da5.firebasestorage.app',
    measurementId: 'G-5DDYDYRST0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7QDp0pIj2IGw0Q15NrJAQPXLO7tAhE90',
    appId: '1:202409214260:android:381eaede3a9195c166e561',
    messagingSenderId: '202409214260',
    projectId: 'slideme-87da5',
    storageBucket: 'slideme-87da5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcd8wRfN3IWJoHtCzc6VXKghp4ltSvU6Q',
    appId: '1:202409214260:ios:0f630f65cb18a68e66e561',
    messagingSenderId: '202409214260',
    projectId: 'slideme-87da5',
    storageBucket: 'slideme-87da5.firebasestorage.app',
    iosClientId: '202409214260-los88ld879r5r26ueamp1tfmkgvivr8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.slideme',
  );
}
