# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

use_frameworks!
use_modular_headers!

# Flutter Pod setup
flutter_application_path = '../'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb') if File.exist?(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb'))
load File.join(flutter_application_path, 'Flutter', 'podhelper.rb') if File.exist?(File.join(flutter_application_path, 'Flutter', 'podhelper.rb'))

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  install_all_flutter_pods(flutter_application_path)
end
